gradleVersion=8.9.0
javaVersion=17
kotlin.stdlib.default.dependency=false
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.console=rich
org.gradle.parallel=true
platformDownloadSources=true
platformPlugins=
platformType=IU
platformVersion=LATEST-EAP-SNAPSHOT
pluginGroup=com.mallowigi.permify
pluginName=Permify
pluginSinceBuild=262.0000
pluginUntilBuild=271.*
pluginVerifierIdeVersions=2024.2
pluginVersion=1.1.0
publishPassword=
publishToken=
publishUsername=Mallowigi
systemProp.org.gradle.unsafe.kotlin.assignment=true
systemProperty="idea.platform.prefix","DataGrip"